[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[[language]]
name = "html"
roots = [".git"]
language-servers = ["emmet-lsp"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "markdown"
language-servers = ["marksman"]
soft-wrap.enable	= true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""
